### ISSUE TITLE
Loading other javascript modules?

### ISSUE THREAD

**Issue by af** [JXA-Cookbook/JXA-Cookbook#1]
Thanks for putting this wiki together, it's a nice resource as info on JS for Automation is hard to come by! You might want to add a pointer to https://github.com/tylergaw/js-osx-app-examples, which is also handy.

I was wondering if you knew of a way to load another javascript file in these scripts, like node's `require()`. It seems like there should be an obvious/simple way to do this, but I haven't found it yet!

**Comment by sprig** [comment]
Thanks for this tip!

Maybe it is obvious to everyone here, but it took me quite long to realise that 'require' itself can't be imported (e.g. via a 'Library' call), or else anything that one 'require's would be useless.

Just saying it in case someone hits this wall like I did. Incidentally, if anyone knows why this is the case, I'd be happy to know.

**Comment by joedaniels29** [comment]
why can't require be imported? I'm finding things fail, but I don't get why?

**Comment by Tatsh** [comment]
Apple really should consider making this compete with Node, and still have all the OS X stuff, just as with their packaged Python.

**Comment by joedaniels29** [comment]
@sprig definitely hit that wall... for 2 hours.

**Comment by sprig** [comment]
@joedaniels29 frankly I'm not sure what I meant anymore. I think I meant that If you could import require, you could just as well import anything else without require

**Comment by danielbayley** [comment]
> Apple really should consider making this compete with Node, and still have all the OS X stuff, just as with their packaged Python.

They should just ship Node & npm with macOS instead of this crap… and just replace all the OS specific stuff with npm modules to cover it!

**Comment by yoodu** [comment]
@Tatsh I tried it, but have  Error: The network file permission error (-5000)

**Comment by yoodu** [comment]
I optimize the method of [Emulating npm's require()](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Importing-Scripts#emulating-npms-require) to return the object by text, so it can place to the Library（I found the function in Library script can't return a function which will be clear)

Library script:  ~/Library/Script Libraries/jsUtil.scpt
``` javascript
function require_(path) {
  var handle = app.openForAccess(path)
  var contents = app.read(handle)
  app.closeAccess(path)
	
  const objText = `
	let module = { exports: {} }
	let exports = module.exports
	${contents}
	module.exports
	`
  return objText
}
```
Top of script
``` javascript
const { require_ } = Library('jsUtil')
const { test = eval(require_('absolute path of util.js')) //use eval to get the object
```
util.js
``` javascript
module.exports = {
  test: function (val)  {
    console.log('test', val)
    return val
  }
}
```
