### ISSUE TITLE
Root Access?

### ISSUE THREAD

**Issue by JRHutson** [JXA-Cookbook/JXA-Cookbook#16]
I'm trying to follow the instructions on utilizing libraries through Browserify and could use a kick in the right direction.

I have Node installed and have downloaded several packages. 

I can install browserify through the normal install command, but when I try to use "npm install -g browserify" I get a message about not having root access. Is this critical to things functioning? Does the Browserify library have to be installed at a root level in order for JXA to leverage it? If so, is there a workaround to all the restrictions on that access added in El Capitan? Also, for clarity, is browserify giving you access to the NPM packages on the fly or do you have to use it to bundle the library and store a bundled version locally? Any help would be appreciated.

**Comment by JRHutson** [comment]
I've disabled System Integrity Protection following this guide-
http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

and enabled myself as a root user per this video-
https://www.youtube.com/watch?v=qTtVhAEAs2Q

but I still get the same error message. Any ideas?
<img width="677" alt="screen shot 2016-01-06 at 8 31 01 am" src="https://cloud.githubusercontent.com/assets/10876900/12147850/fce01d24-b44f-11e5-9ff5-ab02001c3648.png">

**Comment by Tatsh** [comment]
No it is definitely not critical. Most of the time `-g` is used for convenience to install to `/usr/local/`.

Try using nvm instead. You would still follow the instructions, once nvm and a version of Node is installed. https://github.com/creationix/nvm#install-script
