### ISSUE TITLE
Handling Apple Events (especially open location)

### ISSUE THREAD

**Issue by BigLep** [JXA-Cookbook/JXA-Cookbook#17]
Do you have insight into handle various Apple Events?  Per http://stackoverflow.com/questions/34504937/using-os-x-javascript-for-automation-jxa-to-listen-to-open-location-apple-ev , I'm most concerned with the "open location" Apple Event so can trigger a script from a URL.

**Comment by BigLep** [comment]
BTW, my use case is being able to copy an Outlook message reference as a URL and then click it later and have that message open.  I'll post this working application, once can get it fully converted to JXA.

**Comment by terinjokes** [comment]
@BigLep Did you ever get an answer—or file a radar—for this?

**Comment by BigLep** [comment]
@terinjokes I never did figure this out or get a response.  I haven't filed a radar.  I'll put this on my todo list and paste a link to it when I do (may be a couple weeks).

**Comment by stephancasas** [comment]
The correct function name is `GURLGURL`. When called, it receives the URL (with its prefix), as a single argument of type `String`.

Your application's signature should look something like this:

```js
#!/usr/bin/env osascript -l JavaScript

function GURLGURL(url) {
  const App = Application.currentApplication();
  App.includeStandardAdditions = true;

  App.doShellScript(`echo ${url} > ~/Downloads/url-arg.txt`);
  return true;
}
```
