### ISSUE TITLE
Where is the documentation on methods available?

### ISSUE THREAD

**Issue by mplungjan** [JXA-Cookbook/JXA-Cookbook#19]
Seems there are some thing missing like setTimeout? Is it delay() ?

**Comment by Tatsh** [comment]
All global names (`osascript -l JavaScript <<< 'Object.getOwnPropertyNames(this)' 2>&1 | tr ',' $'\n' | sort -u | pbcopy`):


```
 $
 Application
 Array
 ArrayBuffer
 Automation
 Boolean
 DataView
 Date
 Error
 EvalError
 Float32Array
 Float64Array
 Function
 Infinity
 Int16Array
 Int32Array
 Int8Array
 JSON
 Library
 Map
 Math
 Number
 ObjC
 Object
 ObjectSpecifier
 Path
 Progress
 RangeError
 Ref
 ReferenceError
 RegExp
 Set
 String
 Symbol
 SyntaxError
 TypeError
 URIError
 Uint16Array
 Uint32Array
 Uint8Array
 Uint8ClampedArray
 WeakMap
 WeakSet
 __private__
 console
 decodeURI
 decodeURIComponent
 delay
 encodeURI
 encodeURIComponent
 escape
 eval
 isFinite
 isNaN
 parseFloat
 parseInt
 undefined
 unescape
 NaN
```

**Comment by mplungjan** [comment]
Great (well not great since there seems to be stuff missing from ECMAScript)
Thanks

**Comment by Tatsh** [comment]
`setTimeout` and others are part of the HTML5 standard, where they live on the `window` DOM object, which is not part of ECMAScript.

The equivalent is not `delay` because `delay` is synchronous.

Like any other non-web environment, you need the system equivalent. Those are things like `select()` and `kqueue()` in C. How you get those in and call them properly is a bit of trial and error, but I would like to see a shim of setTimeout()/setInterval() via C calls if you end up making one.

**Comment by umireon** [comment]
@Tatsh 
FYI, I ended up with `NSTimer` based implementation for shimming `setTimeout`, etc.
https://gist.github.com/umireon/d1d449be666053b005e48db48aad6c46

**Comment by Tatsh** [comment]
Very neat. If that's up to the standards of the Wiki code, you can add that in for those who want to use it.

**Comment by Tatsh** [comment]
There are still many things missing to make this compatible with (web) JavaScript without DOM stuff. Just a few things:

```
atob
btoa
crypto
File
FileList
FileReader
```

**Comment by JMichaelTX** [comment]
> FYI, I ended up with NSTimer based implementation for shimming setTimeout, etc.
> https://gist.github.com/umireon/d1d449be666053b005e48db48aad6c46

@umireon , thanks for sharing this.
For those of us not well-versed in ObjC, can you please give us a JXA example of how this is used, should be used? 
How does it compare with the AppleScript `delay()`?

Thanks.

**Comment by umireon** [comment]
@JMichaelTX 

> how this is used, should be used?

My answer on SO would help.
https://stackoverflow.com/questions/37834749/settimout-with-javascript-for-automation/41087510#41087510

> How does it compare with the AppleScript delay()?

`delay()` is blocking and mine is non-blocking.
IMO, `delay()` suffices in usual situations.

**Comment by BrokenFreelancer** [comment]
@umireon Nice! just a couple of days ago before seeing this issue, I added a stub for a new section in the ObjC Bridge page of the wiki about asynchronous functions calls through $.system() and $.NSTimer and added a link to that SO question.

**Comment by Tatsh** [comment]
Closing due to age.
