### ISSUE TITLE
Be more detailed in the File and Folder section

### ISSUE THREAD

**Issue by Tekl** [JXA-Cookbook/JXA-Cookbook#2]
It seems that we can't use the Path() object directly like this:

``` javascript
Path("/path/to/file").name()
```

I haven't found a shorter way than this to just get the name if a file/folder:

``` javascript
Application("System Events").aliases.byName("/path/to/file").name();
```

There seems to be different ways to deal with the file system. For example how to use openForAccess from the Standard additions?

There should be also a short overview of generic methods like byName or links to further documentations.

**Comment by Ontonator** [comment]
You can call `openForAccess` using the current application with standard additions, like so:
```javascript
var app = Application.currentApplication();
app.includeStandardAdditions = true;
app.openForAccess(Path("/path/to/file"));
```
I'm a bit late, but someone may find this later like I did.

**Comment by masochist** [comment]
> app.includeStandardAdditions = true;

@Ontonator, where did you learn of this attribute on `Application` objects? This is what I needed for `app.chooseFile` to work, and I wonder what other methods and attributes it enables. It's not mentioned in the AppleScript Language Guide, at least.

**Comment by criptocodes** [comment]
I tried using @Ontonator 's solution with QuickTime but still getting the same error posted by @Tatsh:

`A privilege violation occurred.`

Any idea of why this might happen?
_(not posting the code as it's identical, just targeting QT instead of current app)_

**Comment by Ontonator** [comment]
I'm not sure why that's happening (although it is happening to me as well). It does seem to happen for other applications as well, and doesn't seem to happen for all commands (`displayDialog`, for example, seems to work fine).

Not that this is a solution, but would it still work if you accessed the file through `Application.currentApplication()` instead of QuickTime?

**Comment by criptocodes** [comment]
@Ontonator strangely, it actually works this way... 🤔

**Comment by JMichaelTX** [comment]
I just posted a file related question here, before I discovered this issue thread.
https://github.com/dtinth/JXA-Cookbook/issues/8#issuecomment-299670316

> Just in case someone would like a challenge, here's one that has stumped all JXA experts so far.
> What is the JXA equivalent of this AppleScript?
> 
> tell application "Finder"
>   set itemList to (selection as alias list)
> end tell
