### ISSUE TITLE
Evaluating Application.running() simpler than the methods now described

### ISSUE THREAD

**Issue by RobTrew** [JXA-Cookbook/JXA-Cookbook#20]
I wonder whether the discussion of checking that an application is running

(at https://github.com/dtinth/JXA-Cookbook/wiki/Getting-the-Application-Instance#checking-that-an-application-is-running-before-using-application )

overlooks the method `.running()` on the Application interface ?

This doesn't seem to incur obvious overhead (doesn't, for example, attempt to launch the app).

``` javascript
if (Application('TaskPaper').running()) {
    // ...
}
```

**Comment by Tatsh** [comment]
Probably does. The checking `ps` output could be moved to somewhere else as it demonstrates more of the bridge and how to mix `NSTask` and how to get shell output of an arbitrary command.

**Comment by Tatsh** [comment]
Also may want to keep how to launch the application in the background, but move it elsewhere.

**Comment by RobTrew** [comment]
(As a footnote, I can see how this evolved – the .running() property was only added with OS X 10.11)

**Comment by Tatsh** [comment]
Good to know. It was basically necessary and a major oversight to lack a simple way to ensure the app is running.

Suggest removing the current on checking for the app, replace with using .running(). Need to organise the rest after that.

**Comment by RobTrew** [comment]
For the moment I've just inserted `.running()` as an OSX 10.11 solution, and reframed the rest as approaches to doing the same on systems still running OSX 10.10 ...

**Comment by wivaku** [comment]
Note sometimes full name is required.
In the example below the short name works if the application is running, but fails if it is not.
When using the full name both work.

```
Things = Application("Things")
Things.running()
// if running: true
// if not running: Error: Application can't be found

Things = Application("/Applications/Things3.app")
Things.running()
// if running: true
// if not running: false
```
