### ISSUE TITLE
TypeScript typings?

### ISSUE THREAD

**Issue by ithinkihaveacat** [JXA-Cookbook/JXA-Cookbook#21]
Anyone know if it's possible to automatically generate `.d.ts` files (i.e. TypeScript ambient typings) from the `.sdef` scripting definition files? That would enable method and property completion and type-checking in all TypeScript-supporting editors.

**Comment by russelldavis** [comment]
Yep, check out https://github.com/JXA-userland/JXA/tree/master/packages/@jxa/sdef-to-dts (see the full repo at https://github.com/JXA-userland/JXA)

**Comment by Tatsh** [comment]
I started this by hand: [index.d.ts](https://gitlab.com/Tatsh/vacuum-mail-app/blob/master/index.d.ts). It's so we can have proper generics and overloads (accept both string and NSString), especially with the bridge.
