### ISSUE TITLE
Does shimming `fs` module of node have any difficulties?

### ISSUE THREAD

**Issue by umireon** [JXA-Cookbook/JXA-Cookbook#24]
Hi there

I have recently ported [EditorConfig for JXA](https://github.com/umireon/editorconfig-jxa) and been surprised so-called `jxa-fs` not yet exists.

Are there any difficulties to implement shims of node's system modules?
That will be very useful because the huge number of libraries from npm can be imported into our JXA ecosystem.

Thanks

**Comment by Tatsh** [comment]
There is a lot of work there. It's all valid JS, so you can certainly [`require`](https://github.com/dtinth/JXA-Cookbook/wiki/Importing-Scripts#executing-an-arbitrary-javascript-file) it once you have fixed how the `require` function works, namely paths and adding `.js` automatically. If `fs` could be imported plus everything it pulls in, then you can shim (or really, replace) the functions that are simply not going to work under JXA. Lot of work to do just to get the first [32 lines of `fs`](https://github.com/nodejs/node/blob/master/lib/fs.js) to load. You also have to shim the `process` global (not too hard).

**Comment by umireon** [comment]
@Tatsh Thanks replying!
Have you ever looked [WebPack's shimming library](https://github.com/jvilk/BrowserFS/tree/master/src)?
They have a massive list of shimming libraries so that almost all node modules can be used on browser.

Moreover, there is great product called [Browserfs](https://github.com/jvilk/BrowserFS/tree/master/src), which gives browsers the ability to use the `fs` module.

Combining them, we can use npm modules without much efforts, isn't it? 🍏

**Comment by Tatsh** [comment]
I guess those would work. You are going to have a very specific shim, the JXA shim version of the above. It seems like maybe you could send a PR to [Browserfs](https://github.com/jvilk/BrowserFS/tree/master/src/backend) with a version of the JXA backend, which will mostly be mapping the `fs` API to `NSFileManager`/etc. On OS X you can use the [`FSEvents` API](https://developer.apple.com/library/content/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html) for things like the `change` event.

You can use the [libuv source](https://github.com/libuv/libuv/blob/1a96fe33343f82721ba8bc93adb5a67ddcf70ec4/src/unix/fsevents.c) for guidance on what APIs to hook onto.

**Comment by ELLIOTTCABLE** [comment]
Ooooo, this is badly needed.

I hadn't seen BrowserFS, that's perfect to hook into. If only I knew TypeScript!
