### ISSUE TITLE
keystroke/using doesn't seem to work

### ISSUE THREAD

**Issue by hildjj** [JXA-Cookbook/JXA-Cookbook#3]
On the System Events page, `se.keystroke('a', { using: 'command down' })` doesn't seem to work for me in a place that `keystroke "a" using {command down}` worked in AppleScript.  I get the error `Named parameters must be passed as an object.`

**Comment by hyunchel** [comment]
@hildjj Thank you for the solution. This saved my day!
It was really confusing for me b/c according to Script Dictionary, methods like `keystroke` and `keycode` were under `Processes Suite` along with `click` method.
The `click` method works just fine on per `UIElement` basis. 😞
