### ISSUE TITLE
How to expose values in Script Libraries

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [JXA-Cookbook/JXA-Cookbook#30]
So, the documentation is a little sparse about *what* is exposed when `Library` access a “Script Library” file:

> To use scripts as libraries, store them in ~/Library/Script Libraries/.
> 
> Suppose you have a script library named toolbox.scpt, which contains the following code:
> 
>     function log(message) {
>         TextEdit = Application('TextEdit')
>         doc = TextEdit.documents['Log.rtf']
>         doc.text = message
>     }

So, I ran a [little test][1] on my own:

```es6
// The documented approach
function one(){                     return true }

// Identifier bindings
         two = function(){          return true }
     var three = function(){        return true }
     let four = function(){         return true }

// Explicit property creation
    this.five = function(){         return true }
;(function(){ return this })()
        .six = function(){          return true }
```

```
> ./test.sh
✓ 1. Function declaration of the global environment
✓ 2. Implicit propery of the objective global environment
✓ 3. Identifier binding on the objective global environment
✗ 4. Identifier binding on the declarative global environment
✓ 5. Explicit property of the objective global environment (via `this` self-ref)
✓ 6. Explicit property of the objective global environment (via anon func)
```

I suppose this should have been obvious, but I was afraid Apple was doing some jiggery-pokery on the backend, specifically and exclusively extracting *only* function-declarations from the global environment or something like that.

Thought this might belong in the Cookbook!

   [1]: https://gist.github.com/ELLIOTTCABLE/12e33473dfb325c9374d0cc873bb5356 "JXA (JavaScript for Automation) ‘Script Library’ exports-test"

**Comment by Tatsh** [comment]
Closing due to age.
