### ISSUE TITLE
Move this repo to an organization

### ISSUE THREAD

**Issue by dtinth** [JXA-Cookbook/JXA-Cookbook#32]
I haven’t edited this book for several years now.

However, there are a lot of content now, thanks to everyone’s contribution!

I started this project when I’m still a JXA novice. I think one of the best way to solidify the knowledge is to write it down and share it with others. I don’t use JXA much anymore, so I stopped working on this. But thanks to the contributors, this project continues to grow. I am very happy that others are doing the same thing.

Now, the majority of contributions are by contributors!

| Lines | User | % |
| -----:| ---- | ----------:|
| 696 | @dtinth | 41.6% |
| 299 | @Tatsh | 17.9% |
| 212 | @ELLIOTTCABLE | 12.7% |
| 185 | @RobTrew | 11.1% |
| 148 | @JMichaelTX | 8.9% |
| 65 | @geoff-codes | 3.9% |

Since I am not maintaining this project anymore and most work is done by contributors nowadays, I think it is not quite right that the project is still attributed to me, I think I should move this repo to a new organization.

If you’re a contributor and would like to take the organization forward, please let me know and I’ll make you an owner of the new org. Thanks everyone for your contributions!

**Comment by Tatsh** [comment]
I am okay with starting an organisation for this. What should the name be? *JXA-Cookbook*?

**Comment by dtinth** [comment]
@Tatsh That would be a good name for it. If you start the organization I can transfer the repo to yours. You can add me to that org as well in case I wanna add some stuff to the repo. Thank you~

**Comment by Tatsh** [comment]
Organisation is created: https://github.com/JXA-Cookbook

**Comment by dtinth** [comment]
@Tatsh Seems like GitHub requires me to have "create repository" permission on that org in order to transfer it... Can you invite me into that org? Thanks!

**Comment by dtinth** [comment]
@Tatsh Oops I missed the invite email. My bad. I will initiate the transfer now~

**Comment by dtinth** [comment]
Transferred.

**Comment by ELLIOTTCABLE** [comment]
Feel free to invite me, if you'd like, as I'm still [doing some](https://github.com/ELLIOTTCABLE/detect-jxa) [JXA-library-work](https://github.com/ELLIOTTCABLE/jxa-async).

**Comment by Tatsh** [comment]
It is not necessary to add you to the project. It is an open wiki for anyone to edit and I have no plans to change that.

Suggestion on your libraries: I think you should make an organisation to officially place JXA-specific libraries, especially shims under. I look for to your GCD-based jxa-async project working.

**Comment by ELLIOTTCABLE** [comment]
@Tatsh yeah, that's what I was thinking — I misunderstood, a bit; I thought this was an attempt to centralize forward-looking development of JXA-quality-of-life tooling, not just a continuation of the wiki.

If my work gets to a non-alpha state and/or sees much in the way of interest, I'll almost certainly bring it out from under my name. I see we think along the same lines. `^_^`
