### ISSUE TITLE
How Do We Search Just the Wiki?

### ISSUE THREAD

**Issue by JMichaelTX** [JXA-Cookbook/JXA-Cookbook#33]
### How Do We Search Just the JXA Wiki?
Maybe it is obvious, but I don't see how to do this.

Do we need to install a Github add-on like this:
https://github.com/linyows/github-wiki-search

**Comment by Tatsh** [comment]
On Google: `site:github.com/JXA-Cookbook/JXA-Cookbook search terms`

The old URL might need to be used until Google catches on.
