### ISSUE TITLE
What is JXA Equivalent of AppleScript "system attribute" ?

### ISSUE THREAD

**Issue by JMichaelTX** [JXA-Cookbook/JXA-Cookbook#37]
What is the JXA equivalent of this AppleScript line:
```applescript
set inst to system attribute "KMINSTANCE"
```

Thanks for all help/suggestions.

**Comment by Tatsh** [comment]
For that case, after importing libc: `var inst = $.getenv('KMINSTANCE')`. Just the environment variable. You can also use `NSProcess` to read that value too IIRC.

Otherwise, if the attribute you want is 4 characters long, it will try to find out the 'gestalt value' with the [Gestalt()](https://developer.apple.com/documentation/coreservices/1471624-gestalt?language=objc) function. What that returns is dependent on the attribute. See the documentation on that. It's all deprecated now so I do not think it's necessary to port.

**Comment by JMichaelTX** [comment]
> For that case, after importing libc: `var inst = $.getenv('KMINSTANCE').`

Thanks.  Maybe I'm doing something wrong, but:
`ObjC.import('libc');`

results in "Error: nothing found to import".

I stumbled across another idea:

```javascript
var app = Application.currentApplication()
app.includeStandardAdditions = true

var sa = app.systemAttribute();

sa

/*
Result:
["TMPDIR", "__CF_USER_TEXT_ENCODING", "HOME", "SHELL", "Apple_PubSub_Socket_Render", "SSH_AUTH_SOCK", "PATH", "LOGNAME", "XPC_SERVICE_NAME", "COMMAND_MODE", "USER", "SECURITYSESSIONID", "XPC_FLAGS"]
*/

sa["USER"]

//-->undefined
```

So `var sa = app.systemAttribute();` appears to work.  I just don't know how to call it to get the value of the environment variable, like "USER".

Any ideas?

**Comment by JMichaelTX** [comment]
> What is the JXA equivalent of this AppleScript line:

Here's the complete JXA script that uses the System Attribute in JXA to get/set Keyboard Maestro Local & Instance Variables:

```javascript
var app = Application.currentApplication()
app.includeStandardAdditions = true

var kmInst = app.systemAttribute("KMINSTANCE");
var kmeApp = Application("Keyboard Maestro Engine")

var myLocalVar = kmeApp.getvariable("Local__MyVar",  {instance: kmInst});
kmeApp.setvariable("Local__FromJXA", {instance: kmInst, to: "Set in JXA Script"})

```

**Comment by Tatsh** [comment]
When you call `systemAttribute()` with no arguments, you just get all the keys (and not values) that are environment variables. If you pass the argument of you want it will return that value. If the value does not exist, it returns `''` (empty string). See [examples](https://developer.apple.com/library/content/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW45) from the documentation.

```js
app = Application.currentApplication()
app.includeStandardAdditions = true

console.log( app.systemAttribute('HOME') ) // /Users/tatsh
console.log( app.systemAttribute('HOME2') === '' ) // true
```

Also note I did get a privilege violation with some apps like Mail. So you may want to use alternative ways to get environment variable values:

To get `HOME` environment variable with C function `getenv()`:

```js
ObjC.import('stdlib')
const getenv = (varName) => {
  // Handle exception: Error: exception raised by object: *** +[NSString stringWithUTF8String:]: NULL cString (-2700)
  try {
    return $.getenv(varName)
  } catch (e) {
    return null
  }
}

getenv('HOME') // /Users/tatsh
```

Not a huge fan of this way. I'd prefer to use `NSProcessInfo`:

```js
ObjC.import('Foundation')

console.log(
    ObjC.unwrap(
        $.NSProcessInfo.processInfo.environment.objectForKey('HOME') // /Users/tatsh or undefined if the key is not set
    )
)
```

**Comment by Tatsh** [comment]
Sorry @JMichaelTX I had this tab open for more than 2 hours so I had no idea you replied. Glad you solved your issue. Hope my post can be helpful.

**Comment by JMichaelTX** [comment]
> Sorry @JMichaelTX I had this tab open for more than 2 hours so I had no idea you replied. Glad you solved your issue. Hope my post can be helpful.

@Tatsh , no problem.  You solution is also a good one to have, particularly the `NSProcessInfo` method.

Thanks for the follow-up.
