### ISSUE TITLE
How to correctly call $.realpath

### ISSUE THREAD

**Issue by ZhouZG** [JXA-Cookbook/JXA-Cookbook#40]
//t.js
#!/usr/bin/env osascript -l JavaScript
ObjC.import('stdlib')
console.log($.realpath("t.js",Ref()))

//test
➜  untitled ./t.js
[1]    86703 segmentation fault  ./t.js
➜  untitled ./t.js
/Users/ZhouG/WebstormProjects/untitled/t.js
➜  untitled ./t.js
osascript(86716,0x7fffada643c0) malloc: *** error for object 0x7fb5b2ca8388: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    86716 abort      ./t.js
➜  untitled ./t.js
osascript(86722,0x7fffada643c0) malloc: *** error for object 0x7fd248525908: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    86722 abort      ./t.js
➜  untitled ./t.js
osascript(86728,0x7fffada643c0) malloc: *** error for object 0x7ff5cec66648: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    86728 abort      ./t.js
➜  untitled ./t.js
osascript(86734,0x7fffada643c0) malloc: *** error for object 0x7ff0765785b8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    86734 abort      ./t.js
➜  untitled ./t.js
/Users/ZhouG/WebstormProjects/untitled/t.js
➜  untitled ./t.js
/Users/ZhouG/WebstormProjects/untitled/t.js

**Comment by Tatsh** [comment]
Like this:

```js
#!/usr/bin/env osascript -l JavaScript
ObjC.import('stdlib')
var y = $.realpath('./move', null)
console.log(y)
```

Don't call `$.free(y)`. It might segfault (sometimes it works).

Output: */Users/tatsh/Downloads*

In your case you need to provide a place in memory to put this, or you can pass `null` as the second argument and get the address of the new memory allocated by `realpath` as shown. This would be done normally with `malloc` but this does not work (or does not work reliably):

```js
#!/usr/bin/env osascript -l JavaScript
ObjC.import('stdlib')
var x = $.malloc(1024)
$.realpath('./move', x)
console.log(x)
// $.free(x)
```

You cannot just pass `Ref()` as the point of `Ref` is to keep a reference for yourself.

I would decorate `$.realpath` to make it easier:

```js
const realpath = (x) => $.realpath(x, null)

const resolved = realpath('somePath')
```

**Comment by ZhouZG** [comment]
Thank you very much! It's OK now
