### ISSUE TITLE
Possible to intercept http link clicks from an app??

### ISSUE THREAD

**Issue by varunkumar** [JXA-Cookbook/JXA-Cookbook#41]
I want to intercept hyperlink clicks in an application (say, Slack) and open in a remote desktop. Is it possible to capture the URL clicked?

**Comment by johnelm** [comment]
https://www.choosyosx.com might help..  assuming you’re wanting to intercept web links (https / http  )

**Comment by varunkumar** [comment]
Yes, this helps.

**Comment by varunkumar** [comment]
FYI,I used Platypus for creating an app wrapping AppleScript
