### ISSUE TITLE
better integrating Objective-C Bridge documentation + proposed expansions

### ISSUE THREAD

**Issue by BrokenFreelancer** [JXA-Cookbook/JXA-Cookbook#42]
The page  [__Using Objective C (ObjC) with JXA__](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-(ObjC)-with-JXA) is missing from the __Table of Contents__ on the [__Home__ ](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki) page of the wiki.

I think it should definitely be there to help navigation.

I can put it there myself, but I thought I'd create an issue anyway to notify the wiki community I've made this little change.

I will put it in the same order as it is on the [__Table of Contents__](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/_Sidebar/_edit) sidebar.

Personally though, I think it would make more sense if this section were indexed after [Shell and CLI Interactions](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Shell-and-CLI-Interactions), but before [Importing Scripts ](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Importing-Scripts) from Other Files.

**Comment by Tatsh** [comment]
Go ahead and make these changes.

[Shell and CLI Interactions](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Shell-and-CLI-Interactions) comes after the **Using Objective C...* section because it has more information about the bridge. See [Calling C Functions and Handling Arguments](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Shell-and-CLI-Interactions#calling-c-functions-and-handling-arguments). Perhaps it should be moved onto the Objective-C page, then your ordering would work.

**Comment by BrokenFreelancer** [comment]
The Objective-C page is already pretty long and needs restructuring, so I wouldn't add anything there that can reasonably fit in another (shorter) existing page.
Part of the reason to put some effort in this edit for me is the hope that maybe having the page better integrated in the flow of the wiki might bring to it some new eyes... and contributing fingers.
That is if with some luck Mojave brings us better JXA implementation instead of just killing it off... [crossing fingers despite eternally pessimistic tendencies] 😅. 

Anyway, I already made the following changes:
- to _improve access to_  __Using Objective C (ObjC) with JXA__, I added that page to the Table of Contents on the Home page.
- to _improve conformity with other pages_, I modified __Using Objective C (ObjC) with JXA__  by:  
   - _removing_ the duplicate title header inside the text of the page
  - and _adding_ the   <kbd><strong>← previous· · · · · · · · · · · · · ·next →</strong></kbd>   "navigation button" </br>on the top right corner of the wiki page.
- to _improve navigation flow of the wiki_, I also _changed_ the "navigation button" on the pages:
   - __User Interaction with Files and Folders__   &   __Shell and CLI Interactions__ </br> so that __Using Objective C (ObjC) with JXAs__  is now placed between them.

I also added a stub for a new section called __Introducing Asyncronous Events to JXA using $.system and $.NSTimer__ 

I'm not sure I am the most qualified person to actually write this section, but I think the potential of the Objective-C Bridge to bring an asynchronous work flow to JXA is potentially THE most powerful feature of the bridge.

And then, is __very__ speculative, but I think in theory it might even be possible to multi thread JXA by connecting different blocks of JavaScript code to different threads targeted by the Objective-C Bridge, although this would be a __very__ advanced hack that I doubt anybody in need of this wiki would dare to attempt and might require. Might also require to disable a number of different system protections... I do __not__ plan to add a section about this last hack to the wiki, just gonna swiftly drop it here in the comment as the [sweetest taboo of JXA](https://www.youtube.com/watch?v=kcPc18SG6uA).

**Comment by Tatsh** [comment]
Mojave doesn’t change anything in JXA from what I can tell.

**Comment by BrokenFreelancer** [comment]
@Tatsh are you using the public beta?
I'm avoiding it for now on my personal macbook because I think some of my work software is not compatible, but from what I've seen so far I would assume that even if nothing in JXA directly changes, there would be some changes in the Apple Events it calls upon?

**Comment by Tatsh** [comment]
Yes I am on the public beta. We'll be lucky if Apple updates their documentation on this stuff. Otherwise we have to assume there are no changes.
