### ISSUE TITLE
How can I create a http request with JXA?

### ISSUE THREAD

**Issue by kkxujq** [JXA-Cookbook/JXA-Cookbook#47]
As the title, I want to create a http request in my JXA script, but I don't know how to create it.

**Comment by Tatsh** [comment]
Use [`NSURLSession`](https://developer.apple.com/documentation/foundation/nsurlsession) with the [Objective-C bridge](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-%28ObjC%29-with-JXA#purpose).

```javascript
$.NSURLSession.sharedSession.dataTaskWithURLCompletionHandler($.NSURL.URLWithString('https://www.google.com'), (data, resp) => {
    console.log(resp.statusCode);
    console.log(ObjC.unwrap($.NSString.alloc.initWithDataEncoding(data, $.NSASCIIStringEncoding)).split('\n')[0]);
```

```
>> $.NSURLSession.sharedSession.dataTaskWithURLCompletionHandler($.NSURL.URLWithString('https://www.google.com'), (data, resp) => { console.log(resp.statusCode); console.log(ObjC.unwrap($.NSString.alloc.initWithDataEncoding(data, $.NSASCIIStringEncoding)).split('\n')[0]); } ).resume
=> undefined
>> 200
<!doctype html><html itemscope=""...
```

**Comment by kkxujq** [comment]
> Use [`NSURLSession`](https://developer.apple.com/documentation/foundation/nsurlsession) with the [Objective-C bridge](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-%28ObjC%29-with-JXA#purpose).
> 
> ```js
> $.NSURLSession.sharedSession.dataTaskWithURLCompletionHandler($.NSURL.URLWithString('https://www.google.com'), (data, resp) => {
>     console.log(resp.statusCode);
>     console.log(ObjC.unwrap($.NSString.alloc.initWithDataEncoding(data, $.NSASCIIStringEncoding)).split('\n')[0]);
> }).resume
> ```
> 
> ```
> >> $.NSURLSession.sharedSession.dataTaskWithURLCompletionHandler($.NSURL.URLWithString('https://www.google.com'), (data, resp) => { console.log(resp.statusCode); console.log(ObjC.unwrap($.NSString.alloc.initWithDataEncoding(data, $.NSASCIIStringEncoding)).split('\n')[0]); } ).resume
> => undefined
> >> 200
> <!doctype html><html itemscope=""...
> ```

**Comment by kkxujq** [comment]
> Objective-C bridge


> Use [`NSURLSession`](https://developer.apple.com/documentation/foundation/nsurlsession) with the [Objective-C bridge](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-%28ObjC%29-with-JXA#purpose).
> 
> ```js
> $.NSURLSession.sharedSession.dataTaskWithURLCompletionHandler($.NSURL.URLWithString('https://www.google.com'), (data, resp) => {
>     console.log(resp.statusCode);
>     console.log(ObjC.unwrap($.NSString.alloc.initWithDataEncoding(data, $.NSASCIIStringEncoding)).split('\n')[0]);
> }).resume
> ```
> 
> ```
> >> $.NSURLSession.sharedSession.dataTaskWithURLCompletionHandler($.NSURL.URLWithString('https://www.google.com'), (data, resp) => { console.log(resp.statusCode); console.log(ObjC.unwrap($.NSString.alloc.initWithDataEncoding(data, $.NSASCIIStringEncoding)).split('\n')[0]); } ).resume
> => undefined
> >> 200
> <!doctype html><html itemscope=""...
> ```

ok, Thanks for your suggestion, I solved my problem with [Objective-C bridge](Thanks for your suggestion, I solved my problem with Objective-C bridge)

🎉 [Getting HTML Source from a URL without a Web Browser](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Using-Objective-C-%28ObjC%29-with-JXA#1-getting-html-source-from-a-url-without-a-web-browser)

**Comment by chrillek** [comment]
Running the above code https://github.com/JXA- ook/JXA-Cookbook/issues/47#issuecomment-541245629 does not give the intended result anymore in Monterey. Using only `ObjC.import('Foundation')` gives an error because `$.NSURLSession.sharedSession` is undefined. Using only `ObjC.import('Cocoa')` does not generate this error but the completion handler is never called, either – there's no output appearing on the console.

**Comment by cherryblossom000** [comment]
On macOS Sonoma, I had to `Objc.import('Cocoa')`, otherwise `$.NSURLSession` is `undefined`.
