### ISSUE TITLE
How to copy image or file to clipboard?

### ISSUE THREAD

**Issue by lll00lll** [JXA-Cookbook/JXA-Cookbook#48]
AppleScript copy image to clipboard by path like this
> set img to POSIX file ("/Users/lll00lll/Library/Documents/temp.jpg")
> set the clipboard to img

but how to translate AppleScript code to JavaScript?

JavaScript like this can copy string to clipboard but not img or file
> var app = Application('Script Editor');
> app.includeStandardAdditions = true;
> app.setTheClipboardTo(str);

or use Objective-C ?but i don't how to edit it to "generalPasteboard.setData"
> $.NSPasteboard.generalPasteboard.clearContents;
> $.NSPasteboard.generalPasteboard.setStringForType($(str), $.NSPasteboardTypeString);

**Comment by Tatsh** [comment]
You have to get the full contents of the file then use $.NSData.dataWithBytes(fileContents, length) and then pass that to setDataForType and you must pass the correct image type in the second argument.

**Comment by Tatsh** [comment]
There's also NSData.dataWithContentsOfFile to make this easier. https://developer.apple.com/documentation/foundation/nsdata/1547226-datawithcontentsoffile?language=objc

**Comment by lll00lll** [comment]
> There's also NSData.dataWithContentsOfFile to make this easier. https://developer.apple.com/documentation/foundation/nsdata/1547226-datawithcontentsoffile?language=objc

i try it like this, but not work
```
let file = $.NSData.dataWithContentsOfFile("/Users/lll00lll/Desktop/temp/123.png")
$.NSPasteboard.generalPasteboard.setDataForType(file, $.NSPasteboardTypePNG)
```

**Comment by Tatsh** [comment]
It works for me if I call `$.NSPasteboard.generalPasteboard.clearContents` first.

**Comment by lll00lll** [comment]
> It works for me if I call `$.NSPasteboard.generalPasteboard.clearContents` first.

i just wanted to send me success to edit it, thank you very much
```
let file = $.NSData.dataWithContentsOfFile("/Users/lll00lll/Desktop/temp/123.png")
$.NSPasteboard.generalPasteboard.clearContents
$.NSPasteboard.generalPasteboard.setDataForType(file, $.NSPasteboardTypePNG)
```
But if need copy a .docx or .js or some other file, how to select the Type? 
seems to be no suitable type here: https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc

**Comment by Tatsh** [comment]
You need to use https://developer.apple.com/documentation/appkit/nspasteboard/1533561-declaretypes?language=objc first

**Comment by Tatsh** [comment]
Also you might not have to do that. `NSPasteboardType` is just `NSString *`. And all of those are UTI strings. If something is binary, and doesn't have a UTI type, you can use `$('public.data')` in JXA. However for docx you might want to use `$('public.zip-archive')`. For JSX you probably want to use `$('public.utf8-plain-text')`.

**Comment by Tatsh** [comment]
Known UTIs: https://escapetech.eu/manuals/qdrop/uti.html

**Comment by Tatsh** [comment]
Also see https://en.wikipedia.org/wiki/Uniform_Type_Identifier#Looking_up_a_UTI

**Comment by lll00lll** [comment]
> Also you might not have to do that. `NSPasteboardType` is just `NSString *`. And all of those are UTI strings. If something is binary, and doesn't have a UTI type, you can use `$('public.data')` in JXA. However for docx you might want to use `$('public.zip-archive')`. For JSX you probably want to use `$('public.utf8-plain-text')`.

thank you, but i can barely use this Obj-c, Somewhat complicated,  no success
```
let file = $.NSData.dataWithContentsOfFile("/Users/lll00lll/Desktop/temp/test.py")
let newType =$.NSPasteboard.generalPasteboard.declareTypesOwner($(['py']), $())
$.NSPasteboard.generalPasteboard.clearContents;
$.NSPasteboard.generalPasteboard.setDataForType(file, newType)
```

UTIs is work, but need to know every file UTl type
```
let file = $.NSData.dataWithContentsOfFile("/Users/lll00lll/Desktop/temp/123.png")
$.NSPasteboard.generalPasteboard.clearContents;
$.NSPasteboard.generalPasteboard.setDataForType(file, $('public.png'))
```

i find another problem
in AppleScript, this code seem copy file self to clipboard, it can paste file to everywhere include finder
```
set img to POSIX file ("/Users/lll00lll/Desktop/temp/123.png")
set the clipboard to img
```
but this JXA Objc, seem copy file content to clipboard, ex it can‘t paste file to finder
```
let file = $.NSData.dataWithContentsOfFile("/Users/lll00lll/Desktop/temp/123.png")
$.NSPasteboard.generalPasteboard.clearContents
$.NSPasteboard.generalPasteboard.setDataForType(file, $.NSPasteboardTypePNG)
```
Is there anything i missing?

**Comment by Tatsh** [comment]
Try using the Pasteboard method writeObjects: method with an array of NSImage instance rather than NSData.

generalPasteboard.writeObjects($([img]))

NSImage has https://developer.apple.com/documentation/appkit/nsimage/1519918-initwithcontentsoffile?language=objc

You must call alloc: $.NSImage.alloc.initWithContentsOfFile

**Comment by lll00lll** [comment]
> Try using the Pasteboard method writeObjects: method with an array of NSImage instance rather than NSData.
> 
> generalPasteboard.writeObjects($([img]))
> 
> NSImage has https://developer.apple.com/documentation/appkit/nsimage/1519918-initwithcontentsoffile?language=objc
> 
> You must call alloc: $.NSImage.alloc.initWithContentsOfFile

it work!
```
let img = $.NSImage.alloc.initWithContentsOfFile("/Users/lll00lll/Desktop/temp/123.png")
$.NSPasteboard.generalPasteboard.clearContents;
$.NSPasteboard.generalPasteboard.writeObjects($([img]))
```
but seems copy content, it also can‘t paste file to finder folder

**Comment by Tatsh** [comment]
Seems you have to pass an array of NSURL objects for Finder to work. See here under 'Update:':

https://stackoverflow.com/a/28505538/374110

**Comment by lll00lll** [comment]
> Seems you have to pass an array of NSURL objects for Finder to work. See here under 'Update:':
> 
> https://stackoverflow.com/a/28505538/374110

very useful, i think the closest answer, please check it
```
let pasteboard. = $.NSPasteboard.generalPasteboard
pasteboard.clearContents
let path = '/Users/lll00lll/Desktop/temp/123.png'
let result = setPropertyListForType($([path]), $.NSFilenamesPboardType)
console.log(result)
```
seem can copy everything

**Comment by Tatsh** [comment]
Added here. https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/User-Interaction-with-Files-and-Folders#copy-a-file-to-pasteboard
