### ISSUE TITLE
Integrating with JXA-Snippets example scripts

### ISSUE THREAD

**Issue by SeamlessIO** [JXA-Cookbook/JXA-Cookbook#49]
Hi I made (JXA-Snippets)[https://github.com/SeamlessIO/JXA-Snippets]  because I was missing a source of JXA examples. 
JXA-Cookbook helped me out quite a bit and I was thinking we could combine the two somehow. Maybe an ingredients section in the Cookbook.

**Comment by Tatsh** [comment]
Closing due to age.
