### ISSUE TITLE
Changing values in applications such as Contacts

### ISSUE THREAD

**Issue by karlcow** [JXA-Cookbook/JXA-Cookbook#5]
It would be nice to have examples of not only reading but also writing to applications from the CLI. Something along: 

```
% osascript -l JavaScript -i
>> contact=Application('Contacts');
=> Application("Contacts")
>> contact.people.byName("John Smith").organization();
=> "Acme Inc."
```
1. How to change the organization `value` (from Acme Inc. to FooBar Co.)?
2. How to create a new entry with encoding issues (utf-8 drum)?
3. How to do tie it  int the CLI (though this one is already answered in one of your sections)?

**Comment by dtinth** [comment]
Something like a quick tour, along the lines of [learn X in Y minutes](http://learnxinyminutes.com/)? That seems like a great idea!

**Comment by RobinsonKameron** [comment]
Yeah Im struggling finding any good examples of how to use the different class/ methods/ objects/ the dictionaries are great. However, they don't give really solid examples, check this out though it has some solid examples [JS for Automation WWDC 2014](https://developer.apple.com/videos/play/wwdc2014/306/) .

**Comment by Et7f3** [comment]
for your question (1) and (3) especially  you can type `contact.people.byName("John Smith").organization = "FooBar Co.";` or `contact.people.byName(argv[1]).organization = argv[2];` if you apply tutorial.
(2) see this (I'll will add a exemple to wiki):
https://stackoverflow.com/questions/47972088/how-to-add-a-group-to-adress-book-app-with-javascript-on-mac-os
