### ISSUE TITLE
Object specifiers and Apple Music

### ISSUE THREAD

**Issue by RSully** [JXA-Cookbook/JXA-Cookbook#50]
Hi there! First, let me just say on behalf of many frustrated Apple Script developers, **thank you** for this resource.

I'd like to start a discussion about a bug(?) I've been dealing with for a while. This is definitely a bug in my application (which I have now [fixed](https://github.com/RSully/alfred-genius/commit/ae6517a8813445665b0c7bfc2828db847d6f3067)), but I wonder if it is a bug in the JXA implementation or not.

I am referring to this part of your documentation: https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/iTunes#getting-the-current-track-an-example-of-specifier-vs-property-access

Simply put, when **not** using what you refer to as an "object specifier", it isn't possible to get the name/artist of the playing track when that track is from Apple Music. When it is a track in my own library (including iTunes In The Cloud, even when streaming and not locally downloaded) it works fine, but whenever it is a track from Apple Music, it fails. 

**Examples**:

<details>
<summary>Example fetching current track using property (e.g. with parenthesis)</summary>

**Code**:

```javascript
var musicApp = Application('com.apple.Music');
if (musicApp.playerState() === 'playing') {
    var track = musicApp.currentTrack();

    console.log(track.name());
}
```

**Replies**, when streaming a song from *iTunes in the Cloud*:

```text
app = Application("Music")
	app.playerState()
		--> "playing"
	app.currentTrack()
		--> app.sources.byId(63).userPlaylists.byId(26027).sharedTracks.byId(26072)
	app.sources.byId(63).userPlaylists.byId(26027).sharedTracks.byId(26072).name()
		--> "Gravity"
```

**Replies**, when streaming a song from *Apple Music*:

```text
app = Application("Music")
	app.playerState()
		--> "playing"
	app.currentTrack()
		--> app.sources.byId(70).playlists.byId(64278).urlTracks.byId(65530)
	app.sources.byId(70).playlists.byId(64278).urlTracks.byId(65530).name()
		--> Error -1728: Can't get object.
```

</details>

<details>
<summary>Example fetching current track using object specifier (e.g. without parenthesis)</summary>

**Code**:

```javascript
var musicApp = Application('com.apple.Music');
if (musicApp.playerState() === 'playing') {
    var track = musicApp.currentTrack;

    console.log(track.name());
}
```

**Replies**, when streaming a song from *iTunes in the Cloud*:

```text
app = Application("Music")
	app.playerState()
		--> "playing"
	app.currentTrack.name()
		--> "Gravity"
```

**Replies**, when streaming a song from *Apple Music*:

```text
app = Application("Music")
	app.playerState()
		--> "playing"
	app.currentTrack.name()
		--> "Little Things"
```

</details>

I'd love some discussion about this, particularly regarding iTunes/Music.app. Does this apply to other types of objects? Does anyone have any idea why this happens? What if I wanted to keep a reference to a previously playing song, am I out of luck?

*(This may be related to #11, but looks like the behavior has either changed, or this was not debugged/discussed enough previously. I'd like to see this issue be kept open for some discussion to occur for a bit.)*

**Comment by Tatsh** [comment]
Not sure what your question is really.

Your code to fix the issue does the same thing for both apps. Also I definitely do not recommend putting that many lines in a try/catch. There are plenty of possible exceptions there not including that the app is missing. Since it's the same code maybe you just want to make a function anyway where you pass the application instance.

Technically a user can have both Music.app and iTunes.app installed but you might consider that an edge case (and I don't know what `Application('com.apple.iTunes')` would do in that case.

**Comment by RSully** [comment]
My question is buried in the bottom 🙂:

> I'd love some discussion about this, particularly regarding iTunes/Music.app. **Does this apply to other types of objects? Does anyone have any idea why this happens? What if I wanted to keep a reference to a previously playing song, am I out of luck?**

***

As far as my code - this is really just for my own use. It's an Alfred workflow that lets me bring up Genius.com lyrics quickly for the currently playing song. If other people started using it, I'd worry more about maintainability since I'd be getting requests to add support for many more music apps and I'd have to actually worry about code quality.

> Your code to fix the issue does the same thing for both apps. 

Sorry for the confusion - the commit I linked to does 2 things: it fixes the bug, and also adds support for Music.app. If you look at it in [split view](https://github.com/RSully/alfred-genius/commit/ae6517a8813445665b0c7bfc2828db847d6f3067?diff=split) it's a bit easier to see. It should have been 2 separate commits, sure, but again this is just a personal project and I was lazy :) 

> Also I definitely do not recommend putting that many lines in a try/catch. There are plenty of possible exceptions there not including that the app is missing.

I'm deliberately catching any exception in those blocks because if something goes wrong fetching the song from that app, then chances are good the user isn't listening to that app and I'd rather just try the next one on the list. I'm not exactly able to do much error handling here - if something goes wrong and the user *isn't* listening to a song in another app, then the end result is the same: it just can't pre-fill your search with the song name/artist, and life moves on.

**Comment by Tatsh** [comment]
>Does this apply to other types of objects?

Yes.

>Does anyone have any idea why this happens?

Object specifiers are 'views', similar to Python's `dict.keys()` which returns a 'view' of the dictionary's keys, including when said dictionary's keys change.

> What if I wanted to keep a reference to a previously playing song, am I out of luck?

I don't know if this would work, but maybe cloning the object? A deep clone might not be necessary.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Examples

**Comment by Tatsh** [comment]
Closing due to age.
