### ISSUE TITLE
How do you get a random number in JXA?

### ISSUE THREAD

**Issue by harshayburadkar** [JXA-Cookbook/JXA-Cookbook#51]
In Applescript it is something like:
`(random number from 3 to 198)`

Any idea about JXA?

P.S. Many thanks for creating this documentation!

**Comment by harshayburadkar** [comment]
Nevermind - I got it figured out. 

If someone is looking:
`const getRandom = (max) => {
	ObjC.import('stdlib')
	return $.arc4random() % max;
}`

**Comment by wodinga** [comment]
Also Math.random, for future reference, since this is JavaScript
