### ISSUE TITLE
How to make FSEventStream Work

### ISSUE THREAD

**Issue by 4r7d3c0** [JXA-Cookbook/JXA-Cookbook#52]
hey it's an awesome project i'm very inspired by jxa i don't know why some people say things like these
![Screenshot 2020-08-03 at 22 28 50](https://user-images.githubusercontent.com/60678477/89243258-2c55e600-d60c-11ea-848e-0a0f9d1d429d.png)
i hate node despite loving it but after years of working with it i'm looking into more native apis so the opportunity to use js like that is just... something. 
but i can't get the first challenge that is to get fsevents, here's the code

```js
ObjC.import("CoreServices")
ObjC.import('stdlib')
 
ObjC.bindFunction('malloc', ['void**', ['int']])
// ObjC.bindFunction('CFStringCreateWithCString', ['void**', ['nil', 'string', 'string']])

app = Application.currentApplication()
app.includeStandardAdditions = true

function string2Pointer(string) {
  const cfs = $. CFStringCreateWithCString(null, `${string}\0`, 'UTF-8')
  console.log('string-pointer', cfs)
  return cfs
}

const PATH = '/Users/anton/abc.txt'
const PATHS = [PATH]

const pointers = $.malloc(PATHS.length * 8)

PATHS.map((p, i) => {
  const cfstp = string2Pointer(p)
  console.log(i, p, cfstp, readFile(p))
  pointers[i] = cfstp 
})

function readFile (path, encoding = $.NSUTF8StringEncoding) {
    const fm = $.NSFileManager.defaultManager
    const data = fm.contentsAtPath(path)
    const str = $.NSString.alloc.initWithDataEncoding(data, encoding)
    return ObjC.unwrap(str)
}

const cfarrayRef = $.CFArrayCreate($.kCFAllocatorDefault, pointers, PATHS.length, null)
console.log(cfarrayRef)

stream = $.FSEventStreamCreate($.kCFAllocatorDefault,  // https://developer.apple.com/documentation/coreservices/1443980-fseventstreamcreate?language=occ
        function() {
			app.displayAlert('change')
			console.log('some change')
			$.NSLog('some change')
		},
        null, 
        cfarrayRef,
        $.kFSEventStreamEventIdSinceNow, /* Or a previous event ID */
        3,
        $.kFSEventStreamCreateFlagUseCFTypes /* Flags explained in reference */
    ) 
	
$.FSEventStreamScheduleWithRunLoop(stream, $.CFRunLoopGetCurrent, $.kCFRunLoopDefaultMode)
$.FSEventStreamStart(stream)
$.CFRunLoopRun
app.displayAlert(`Watching ${PATHS.join(', ')}`)

//app.quit()
```

`FSEventStreamCreate`: https://developer.apple.com/documentation/coreservices/1443980-fseventstreamcreate?language=occ
`Minimum example of FSEvent`: https://gist.github.com/yangacer/6037073 

I've seem to have done it all right even casting malloc to pointers like suggested here https://stackoverflow.com/questions/49263671/obtaining-a-list-of-class-names-with-objc-getclasslist-in-javascript-for-automat still when i edit the file, nothing happens. could it be because i can't pass callback functions like this? what's wrong :(( 

thank you 😌

[File System Events Programming Guide
](https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html)
- [CFStringCreateWithCString](https://developer.apple.com/documentation/corefoundation/1542942-cfstringcreatewithcstring?language=objc:)
> cStr
> The NULL-terminated C string to be used to create the CFString object. The string must use an 8-bit encoding.

**Comment by Tatsh** [comment]
I got `malloc` to work with:

```
ObjC.bindFunction('malloc', ['void*', ['int']]);
```

`malloc` then returns `Ref<number>`.

https://github.com/tatsh/jxa-lib#example-with-c-functions

I feel like you shouldn't have to create a CFArray like that (or strings). You should be able to pass a converted JavaScript array (which is converted to NSArray, and JXA will convert it to CFArray with toll-free bridging).

```javascript
$.FSEventStreamCreate(null,
        function() {
			app.displayAlert('change')
			console.log('some change')
			$.NSLog('some change')
		},
        null, 
        ObjC.wrap([ObjC.wrap('/Users/anton/abc.txt')]),
        $.kFSEventStreamEventIdSinceNow, /* Or a previous event ID */
        3,
        $.kFSEventStreamCreateFlagUseCFTypes /* Flags explained in reference */
    ) 
```

**Comment by Tatsh** [comment]
The issue with this function is how to get the callback passed. I don't know if there is a way. This same kind of code in C works fine. `$.FSEventStreamShow` always shows a null pointer for callback:

```
FSEventStreamRef @ 0x7f8d6221caf0:
   allocator = 0x7fff8c791cc0
   callback = 0x0
   f2d_private_port = 0x4d03
   context = {0, 0x0, 0x0, 0x0, 0x0}
   numPathsToWatch = 1
   pathsToWatch = 0x7f8d6221c090
        pathsToWatch[0] = '/System/Volumes/Data/Users/tatsh/Downloads'
   numPathsToExclude = 0
   latestEventId = -1
   latency = 0 (microseconds)
   flags = 0x00000010
   runLoop = 0x7f8d60605180
   runLoopMode = 0x7fff8c7d7b00
```

**Comment by Tatsh** [comment]
You can re-bind the C functions with `void*` and get a value with `Ref`:

```javascript
ObjC.import("CoreServices");
ObjC.import("dispatch");

ObjC.bindFunction("FSEventStreamCreate", [
  "void*",
  ["void*", "void*", "void*", "void*", "int", "int", "int"],
]);
ObjC.bindFunction("FSEventStreamScheduleWithRunLoop", [
  "void",
  ["void*", "void*", "void*"],
]);
ObjC.bindFunction("FSEventStreamStart", ["bool", ["void*"]]);
ObjC.bindFunction("FSEventStreamShow", ["void", ["void*"]]);

const paths = $.CFArrayCreateMutable(null, 1, null);
$.CFArrayAppendValue(
  paths,
  $.CFStringCreateWithCString(
    null,
    "/Users/tatsh/Downloads",
    $.kCFStringEncodingUTF8
  )
);

const ref = new Ref("void*");
ref[0] = function () {
  console.log("a change");
};

const stream = $.FSEventStreamCreate(
  null,
  ref,
  null,
  paths,
  $.kFSEventStreamEventIdSinceNow,
  0,
  $.kFSEventStreamCreateFlagFileEvents
);
$.FSEventStreamScheduleWithRunLoop(
  stream,
  $.CFRunLoopGetCurrent(),
  $.kCFRunLoopDefaultMode
);
$.FSEventStreamStart(stream);

$.FSEventStreamShow(stream);

$.CFRunLoopRun();
```

This will show a callback pointer is given but I'm pretty sure it is wrong because this code does not trigger the callback and it crashes with *Bus error* eventually.

One way to investigate this would be to disable SIP, run LLDB against `osascript`, and inspect the memory.

**Comment by 4r7d3c0** [comment]
@Tatsh hey man thanks a lot for these responses I appreciate it! I'll inspect them better this week and let you know if I could get more results (after playing with osa, I've decided to go with a more integrated custom-written solution with JS via JSContext) - I'm making my own node similar to https://www.nexusjs.com, but it feels like using [osa](http://18.206.198.104/downloads/MacOSX10.8.sdk/System/Library/Frameworks/OSAKit.framework/Headers/OSAScript.h) is a redundant step.
 
Also my code wasn't actually 100 correct because it had to use `kFSEventStreamCreateFlagFileEvents` to react to files...
