### ISSUE TITLE
Arrow functions now work in shebang files

### ISSUE THREAD

**Issue by mikelei8291** [JXA-Cookbook/JXA-Cookbook#54]
![Screenshot](https://user-images.githubusercontent.com/9620335/95812510-7e527080-0d0d-11eb-86c0-81466e932224.png)

https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/ES6-Features-in-JXA#arrow-functions

**Comment by Tatsh** [comment]
Please update the wiki.

**Comment by mikelei8291** [comment]
Fixed
