### ISSUE TITLE
Using Javascript in OS X Script Editor

### ISSUE THREAD

**Issue by RobTrew** [JXA-Cookbook/JXA-Cookbook#6]
Perhaps this is tangential to JXA, but do we know the format / API for Yosemite Script Editor plug-ins ?

( as in Script Editor > Preferences > Plugins )

( Raw Script Editor has quite limited built-in support for JXA  – no automatic reformatting, indenting, quoting – and filling these gaps with [scripts](https://github.com/dtinth/JXA-Cookbook/wiki/Script-Editor) yields slowish performance ... )

I haven't seen any documentation for these plug-ins ...

**Comment by dylan-chong** [comment]
I know this doesn't answer the question, but if you hate the script editor, you can save the script as a text file and then edit the file in vim or whatever. You can then call the script with `osa -l JavaScript path/to/the/script`, or better yet, setting up gulp watch to auto-run your script. That's what I did just recently (checkout [my repo](https://github.com/dylan-chong/itunes-applescripts) to `6d47fbb`),

**Comment by RobTrew** [comment]
Yes, I do think an alternative editor works better. I now use two packages in Atom, which enables me to run JavaScript for Automation code in the editor by tapping ⌘I

- https://atom.io/packages/language-javascript-jxa
- https://atom.io/packages/script

The only limitation of alternative editors is that [using the Safari debugger with JXA](https://developer.apple.com/library/mac/releasenotes/InterapplicationCommunication/RN-JavaScriptForAutomation/Articles/OSX10-11.html#//apple_ref/doc/uid/TP40014508-CH110-SW1) is only enabled for the Script Editor.app context, so for debugging you may need to switch back into it.

To add things like comment-toggling, block indent/outdent etc, (for the times when you do need Script Editor), you can put JXA macros into the SE Script Library folder, and bind keystrokes to them.

**Comment by ELLIOTTCABLE** [comment]
@RobTrew Er, are you sure about that? or do you mean something other than how I parsed it, or has it changed in the year since? Because I refuse to touch Script Editor, and have definitely been having `osascript` invocations with `debugger;` statements launching Safari w/ the Web Inspector!

**Comment by RobTrew** [comment]
That sounds good. How are you running the scripts, and what are your Safari > Developer settings ?

Are you getting a debugger activation from running a shell script like this, for example:
```
osascript -l JavaScript <<JXA_END 2>/dev/null
	debugger;
	Application('Finder').selection().length
JXA_END
```

**Comment by JMichaelTX** [comment]
> Are you getting a debugger activation from running a shell script like this, for example:

**Confirmed!**

I did get the Safari debugger activation using your shell script,
running Safari 10.1 (11603.1.30.0.34) on macOS 10.11.6
