### ISSUE TITLE
Side-by-side JXA/AppleScript Example(s)

### ISSUE THREAD

**Issue by ghost** [JXA-Cookbook/JXA-Cookbook#8]
There are tons of resources and existing scripts for AppleScript on the web, but not so many for JXA. It would be nice to see some examples with equivalent scripts written in both JXA and AppleScript, so that newbies could see how the languages map to one another.

**Comment by JMichaelTX** [comment]
I agree, that would be helpful.  Unfortunately you request seems have fallen on deaf ears.

### Challenge
Just in case someone would like a challenge, here's one that has stumped all JXA experts so far.
What is the JXA equivalent of this AppleScript?

```applescript
tell application "Finder"
  set itemList to (selection as alias list)
end tell
```

It is the "as alias list" that seems to be the hard part.
According to the Finder SDEF:

> **AliasList** Object : A list of aliases. Use ‘as alias list’ when a list of aliases is needed (instead of a list of file system item references).

However, I cannot figure out how to use "**AliasList**" with JXA.

**Comment by Tatsh** [comment]
These `as some_type` statements do not appear to have an equivalent in JXA. Would be a cast otherwise.

Try literally? Get the file references (probably a regular `[]`) and use `CFURLCreateBookmarkData()` to convert them all to aliases in another `[]`. You have to adjust the argument data types for `CFURLCreateBookmarkData()` for this to work.

**Comment by Ontonator** [comment]
Try this:
`var Finder = Application("Finder");
var SystemEvents = Application("System Events");

var itemList = Finder.selection().map(e => SystemEvents.aliases[decodeURIComponent(e.url().substring(7))]());`

**Comment by Tatsh** [comment]
Closing due to age.
