### ISSUE TITLE
Need Help with richtext - Maybe an example?

### ISSUE THREAD

**Issue by thedangler** [JXA-Cookbook/JXA-Cookbook#9]
I've searched high and low for how to do this and I can't seem to figure out how to extract presentationNotes from a Keynote presentation. I'm trying to extract all the presentationNotes and placing them into .txt file.  However no matter what 
document.slides[0].presentationNotes returns an object specifier so does document.slides[0].presentationNotes.words[0] 
I simply cant see the notes and trying put them in a textEdit application document doesn't seem to work either.
Any help would be appreciated.

**Comment by RobTrew** [comment]
I think the name of the function is `.presenterNotes()`

```
(function () {
	'use strict';

	var KeyNote = Application("Keynote"),
		slides = KeyNote.documents[0].slides;

	return slides().map(function (x) {
		return {
			title: x.defaultTitleItem.objectText(),
			body: x.defaultBodyItem.objectText.paragraphs(),
			notes: x.presenterNotes()
		};
	})

})();
```
